### ISSUE TITLE
Host on Github Pages

### ISSUE THREAD

**Issue by Potherca** [gameblabla/doodle-champion-island-games-Google#2]
If the main HTML file is renamed to `index.html` and GitHub Pages enabled, the game would be hosted and could also be linked to online!

**Comment by gameblabla** [comment]
Should i even do that ? The game isn't mine you know. But yes, it would work.

**Comment by Potherca** [comment]
I've done the same here: [potherca-blog/Google-Doodle-Champion-Island](https://github.com/potherca-blog/Google-Doodle-Champion-Island) / https://blog.pother.ca/Google-Doodle-Champion-Island/.

Worste-case you get a cease-and-desist and need to take it down again. :shrug:

**Comment by niutech** [comment]
Why on Github Pages? It's already at https://www.google.com/logos/2020/kitsune/rc6/kitsune20.html

**Comment by Potherca** [comment]
@niutech If/when things change, its good to have a copy. Also, for whatever reason, we might want to make changes.

So why not?

**Comment by gameblabla** [comment]
Well whatever, i realized that some people may have google.com blocked (China etc...) or simply may not want to go on google.com so enabled Github Pages and fixed some potential issues. If Google goes after me, so be it.

**Comment by niutech** [comment]
@gameblabla Could you add the link to https://gameblabla.github.io/doodle-champion-island-games-Google/ in the repository description?

**Comment by gameblabla** [comment]
Sure, will do.
