### ISSUE TITLE
How to change the language?

### ISSUE THREAD

**Issue by ghost** [gameblabla/doodle-champion-island-games-Google#9]
I'm a newbie, i'm playing at this https://gameblabla.github.io/doodle-champion-island-games-Google/ and i want to change the language but i don't know how, can you show me how to change the language?

**Comment by gameblabla** [comment]
https://github.com/gameblabla/doodle-champion-island-games-Google/blob/simp/index.html#L478
You can change it here

**Comment by ghost** [comment]
Thank you and sorry to bother but i really don't know how to change and how to launch it after change. I tried downloading code as zip and run index.html but it didn't work :(

**Comment by gameblabla** [comment]
What do you mean it doesn't work ?
You have this line in index.html
`google.doodle.hl = "en";`
And you can change it to anyone of the languages in the repo.
So for example for French, it would be :
`google.doodle.hl = "fr";`
or for Chinese, it's 
`google.doodle.hl = "zh-CN";`

You just need to download a copy of this repo, make the changes and then run index.html (as explained in the README).
Alternatively, you can fork the repo, change the language as i told you and then enable github pages on your repo.

I can definitively tell you it worked as i've just tried it myself.

**Comment by ghost** [comment]
Sorry for not being clear, I mean, when I downloaded it as a zip and ran the index.html file in my chrome browser but I couldn't click the play button to launch the game. Do I need a special browser or a server or something? Since I'm just a normal user, I'm not very familiar with these things and I'm new to github too, there's a lot of stuff here that I need to learn. 😆

**Comment by gameblabla** [comment]
> Sorry for not being clear, I mean, when I downloaded it as a zip and ran the index.html file in my chrome browser but I couldn't click the play button to launch the game. Do I need a special browser or a server or something?

This is a well known issue with Chrome/Chromium. They locked down local reads so the only way for chrome based browsers is to either host a local server (as explained in the README) :

```
Yyou will need to host your own HTTP server. Run : python3 -m http.server
in a terminal and load up the game at 127.0.0.1:8000.
```
Or you can, as i stated before, fork it and change the language to whatever you want and enable github pages (Settings -> Pages. Then in source, select the "simp" branch" and save)

You can also use Firefox : it can read local files just fine.
